name: bond_notifications
description: Bond package provides a convenient way to handle notifications.
version: 0.0.1+5
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bond_core: ^0.0.1+5
  bond_network: ^0.0.3+1

