name: bond_form_bloc
description: Form is a Bond package provides a convenient way to handle Form using Getx.
version: 0.0.1+1
repository: https://github.com/onestudio-co/bond-core/tree/main/packages/form/packages/bond_form_getx
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  bond_form: ^0.0.22+5
