name: bond_form_getx
description: Form is a Bond package provides a convenient way to handle Form using Getx.
version: 0.0.2
repository: https://github.com/onestudio-co/bond-core/tree/main/packages/form/packages/bond_form_getx
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2

  bond_form: ^0.0.8+1